spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /yaojie
    username: yaojie
    password: yaojie
    listener:
      simple:
        acknowledge-mode: manual
      type: simple
    publisher-returns: true

